name: caronafront
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.2
  intl: ^0.19.0
  multiselect_formfield: ^0.1.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  iconsax: ^0.0.8
  flutter_chat_bubble: ^2.0.2


flutter:
  uses-material-design: true
  assets:
    - assets/Images/logoapp.png
    
